name: France 24

on:
  schedule:
    - cron: '08 */3 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Félix"

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y openvpn && pip install requests

      - name: Setup VPN connection
        env:
          VPN_CONFIG: ${{ secrets.VPN_CONFIG }}
          VPN_USER: ${{ secrets.VPN_USER }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
        run: |
          printf "%s" "$VPN_CONFIG" > vpnconfig.ovpn
          echo -e "$VPN_USER\n$VPN_PASSWORD" > vpn_credentials.txt
          sudo openvpn --config vpnconfig.ovpn --auth-user-pass vpn_credentials.txt --daemon
          rm -f vpn_credentials.txt

      - name: Verify VPN connection
        run: curl ifconfig.me
      
      - name: Update France 24
        run: python3 Stream/Python/France24.py > Stream/Live/France24.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull origin main
          git commit -m "Update" -m "France 24"
          git push origin main
