name: LCI Stream

on:
  schedule:
    - cron: '08 */3 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "LCI Bot"
      
      - name: Update LCI
        run: python3 Stream/Python/LCI.py > Stream/Live/LCI.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull origin master
          git commit -m "Stream 'LCI' mis à jour."
          git push origin master
